### ISSUE TITLE
Error on Cost Management Query

### ISSUE THREAD

**Issue by hugomf** [Azure/azqr#277]
When I run this command:

azqr scan --filters filter.yaml --json    

filter.yaml
azqr:
  include:
    subscriptions:
      - "xxxx-xxxx-xxx-xxx-xxxx"
    resourceGroups:
      - "/subscriptions/xxxx-xxxx-xxx-xxx-xxxx/resourceGroups/MaDataEng-Dev"
    services:
      - "Microsoft.KeyVault/vaults"
      - "Microsoft.Storage/storageAccounts"
      - "Microsoft.DataFactory/factories"
      - "Microsoft.Sql/servers"
      - "Microsoft.Sql/servers/databases"

  exclude:
    services:
      - "Microsoft.CostManagement/query"

I got this error:

`FTL Failed to query costs error="POST https://management.azure.com/subscriptions/xxxx-xxx-xxx-xxxxx-xxxxxxxx/providers/Microsoft.CostManagement/query\n--------------------------------------------------------------------------------\nRESPONSE 401: 401 Unauthorized\nERROR CODE: RBACAccessDenied\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"RBACAccessDenied\",\n    \"message\": \"The client does not have authorization to perform action. Request ID: aefe2d4c-3134-4658-b9d1-f6a1b5c96cb2\"\n  }\n}\n--------------------------------------------------------------------------------\n"`

I understand the problem, **Cost Management Reader role** is needed,  but if I run it like this with the same subscription:

azqr scan -s "xxxxx-xxx-xxx-xxxx" -g "MaDataEng-Dev"

I don't get any error and xlsx file is generated, why if I supposed to filter more with the first command?

**Comment by cmendible** [comment]
Hi @hugomf,

currently the filters file only allows to **exclude services by id** and there is no `services` property in the `include` section:

```yaml
azqr:
  include:
    subscriptions:
      - <subscription_id> # format: <subscription_id>
    resourceGroups:
      - <resource_group_resource_id> # format: /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>
  exclude:
    subscriptions:
      - <subscription_id> # format: <subscription_id>
    resourceGroups:
      - <resource_group_resource_id> # format: /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>
    services:
      - <service_resource_id> # format: /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/<service_provider>/<service_name>
    recommendations:
      - <recommendation_id> # format: <recommendation_id>
```

So, in your case:

This section is ignored: 

```yaml
services:
- "Microsoft.KeyVault/vaults"
- "Microsoft.Storage/storageAccounts"
- "Microsoft.DataFactory/factories"
- "Microsoft.Sql/servers"
- "Microsoft.Sql/servers/databases"
```

And this section has no effect because there is no service with such id:

```yaml
services:
- "Microsoft.CostManagement/query"
```

Now regarding the error, can you confirm you have the built-in Reader role assigned at the subscription level? If not, you can ignore costs when running a scan setting the following flag: `-c=false`

For example: `azqr scan -s xxxx-xxxx-xxx-xxx-xxxx -g MaDataEng-Dev -c=false` will scan al services in the given resource group ignoring costs.

> Note: I will create an issue, so we add a `resourceTypes` property under the include section in order to tell `azqr` to scan a subset of services.
