### ISSUE TITLE
Improve Filtering to allow setting resourceTypes to scan

### ISSUE THREAD

**Issue by cmendible** [Azure/azqr#278]
## Describe the feature

Current filtering options fall short if user wants to scan just a subset of resource types (i.e. only scan storage, key vaults and SQL servers).

A new `resourceTypes` property under the `include` section should be added:

```yaml
azqr:
  include:
    subscriptions:
      - <subscription_id> # format: <subscription_id>
    resourceGroups:
      - <resource_group_resource_id> # format: /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>
    resourceTypes:
      - <resource type to be included>
  ...
```

For context check https://github.com/Azure/azqr/issues/277 which shows what some users are attempting to do.
