### ISSUE TITLE
Running AZQR from Azure DevOps Pipeline returns empty results

### ISSUE THREAD

**Issue by ryan-rosenburg** [Azure/azqr#289]
I've installed azqr locally, logged in with Az CLI, and run the app pointed to a Subscription and a Resource Group; it returns the expected spreadsheet with all of the resource details.

I'm trying to set this up in an Azure DevOps pipeline to make it easier for our teams to run. The pipeline is using the AzureCLI@2 task, logging into Azure with a Federated Service Connection which has Contributor access to the Management Group level. We use the same Service Connection under the same AzureCLI@2 task to deploy resources, so I know the task is correctly authenticated to our tenant with the Contributor level of access to all the Subscriptions and Resource Groups in the Management Group.

AZQR does not fail or throw any errors. It returns an Excel spreadsheet, but the tabs only have the headers and no resources listed.

## Expected Behavior

Execute azqr from a AzureCLI@2 pipeline task and have it return identical results as if running locally
AzureCLI@2 pipeline task runs Az Login in the background as the service principal of the service connection, and adds the SPN to the environment variables.

## Actual Behavior

AzureCLI@2 task authenticates to Azure, azqr successfully runs against a subscription and resource group, and the spreadsheet is created. But the spreadsheet does not contain any resources.

![Image](https://github.com/user-attachments/assets/c2c6ef4c-4311-466b-af58-322ec317a290)
![Image](https://github.com/user-attachments/assets/28db96ad-d2d7-4cb2-8b13-856614b6705d)

**Comment by cmendible** [comment]
Hi,

can you try running adding the environment variables (AZURE_CLIENT_ID, AZURE_CLIENT_SECRET & AZURE_TENANT_ID) as in the following pipeline:

```yaml
# azqr pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    latest_azqr=$(curl -sL https://api.github.com/repos/Azure/azqr/releases/latest | jq -r ".tag_name" | cut -c1-) \
    && wget https://github.com/Azure/azqr/releases/download/$latest_azqr/azqr-ubuntu-latest-amd64 -O /usr/local/bin/azqr \
    && chmod +x /usr/local/bin/azqr
  displayName: 'Install azqr'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'management_group'
    addSpnToEnvironment: true
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      export AZURE_CLIENT_ID=$servicePrincipalId
      export AZURE_CLIENT_SECRET=$servicePrincipalKey 
      export AZURE_TENANT_ID=$tenantId
      timestamp=$( date '+%Y%m%d%H%M%S' )
      echo "##vso[task.setvariable variable=DATETIME]$timestamp"
      azqr scan -o "$(System.DefaultWorkingDirectory)/azqr_action_plan_$timestamp"
  displayName: 'Run azqr scan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: "$(System.DefaultWorkingDirectory)/azqr_action_plan_$(DATETIME).xlsx"
    artifact: 'azqr_result'
    publishLocation: 'pipeline'
  displayName: 'Publish azqr action plan'
``` 

> I can confirm it's working with a service connection to the root management group.
